### ISSUE TITLE
denyrev doesn't seem to work

### ISSUE THREAD

**Issue by lzs** [oiv/denyactions#1]
@oiv Hi... the denyrev doesn't seem to work. I have:

$conf['plugin']['denyactions']['denyactions'] = 'revisions';
$conf['plugin']['denyactions']['denyrev'] = 1;

But old revisions are still accessible to READ users.

In fact, I don't see how the action/*php are included?

**Comment by lzs** [comment]
Also a warning in error_log:
AH01071: Got error 'PHP message: PHP Warning:  Declaration of action_plugin_denyactions::register(Doku_Event_Handler &$controller) should be compatible with DokuWiki_Action_Plugin::register(Doku_Event_Handler $controller) in /opt/www/html/lib/plugins/denyactions/action.php on line 0\n', referer: https://xxx/sandbox/start

**Comment by oiv** [comment]
Oh. Sorry. Forgot add info that you need to either uninstall and then reinstall the plugin or you can manually delete the actions.php.
The plugin manager has no way (that I know) to delete files which are not in new version. Alla actions are now in actions/*.php which are handled automagically by dokuwiki.

**Comment by lzs** [comment]
Thanks! Ok, denyrev sort of works now... but it works for everyone, i.e. everyone can't read old revisions. My intent was only for READ users to be affected. Is this your intended behaviour? :)

**Comment by oiv** [comment]
Ouch. Sorry no. Ofcourse the "last minute change" broke it. I'll make a fix for it quickly.

**Comment by oiv** [comment]
Ok. The updated version _should_ work now...

**Comment by lzs** [comment]
Thank you... it's perfect now! :)
